In [29]:
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen

In [30]:
url='https://www.dhs.gov/immigration-statistics/yearbook/2017/table3'
html=urlopen(url).read()

In [31]:
soup=BeautifulSoup(html,'html.parser')

In [32]:
table3={
    'Region of Birth':[],
    '2015':[],
    '2016':[],
    '2017':[]
}

In [33]:
tables = soup.find_all('table')
rows = tables[0].find_all('tr')[1:]

In [34]:
for r in rows:
    col1=r.find_all('th')
    col2=r.find_all('td')
    table3['Region of Birth'].append(col1[0].get_text())
    table3['2015'].append(col2[0].string)
    table3['2016'].append(col2[0].string)
    table3['2017'].append(col2[0].string)

In [35]:
table3

{'Region of Birth': ['\xa0\xa0\xa0\xa0\xa0 Total',
  'Africa',
  'Asia',
  'Europe',
  'North America',
  'Oceania',
  'South America',
  'Unknown'],
 '2015': ['1,051,031',
  '101,415',
  '419,297',
  '85,803',
  '366,126',
  '5,404',
  '72,309',
  '677'],
 '2016': ['1,051,031',
  '101,415',
  '419,297',
  '85,803',
  '366,126',
  '5,404',
  '72,309',
  '677'],
 '2017': ['1,051,031',
  '101,415',
  '419,297',
  '85,803',
  '366,126',
  '5,404',
  '72,309',
  '677']}

In [36]:
table4={
    'Region of Birth':[],
    '2015':[],
    '2016':[],
    '2017':[]
}

In [37]:
tables1 = soup.find_all('table')
rows1 = tables[1].find_all('tr')[1:]

In [38]:
for r in rows1:
    col1=r.find_all('th')
    col2=r.find_all('td')
    table4['Region of Birth'].append(col1[0].get_text())
    table4['2015'].append(col2[0].string)
    table4['2016'].append(col2[0].string)
    table4['2017'].append(col2[0].string)

In [39]:
table4

{'Region of Birth': ['\xa0\xa0\xa0\xa0\xa0 Total',
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burma',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  "China, People's Republic",
  'Colombia',
  'Comoros',
  'Congo, Democratic Republic',
  'Congo, Republic',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Czechoslovakia (former)',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South 1',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia, Federated States',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles (former)',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Serbia and Montenegro (former)',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Soviet Union (former)',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Virgin Islands, British',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'All other countries 2',
  'Unknown'],
 '2015': ['1,051,031',
  '8,328',
  '4,653',
  '1,775',
  '-',
  '154',
  '22',
  '290',
  '3,730',
  '2,962',
  '38',
  '3,034',
  '474',
  '676',
  '725',
  '145',
  '13,570',
  '376',
  '1,994',
  '662',
  '772',
  '466',
  '112',
  '6,325',
  '1,626',
  '859',
  '61',
  '11,424',
  '21',
  '2,688',
  '575',
  '12,808',
  '351',
  '1,253',
  '1,868',
  '4,374',
  '12,673',
  '53',
  '234',
  '175',
  '1,596',
  '74,558',
  '17,316',
  '5',
  '5,345',
  '496',
  '2,029',
  '1,497',
  '348',
  '54,396',
  '22',
  '113',
  '637',
  '58',
  '609',
  '370',
  '229',
  '50,610',
  '10,187',
  '12,085',
  '19,487',
  '25',
  '2,220',
  '189',
  '11,394',
  '875',
  '407',
  '4,693',
  '14',
  '146',
  '1,142',
  '1,410',
  '5,436',
  '6,186',
  '1,211',
  '525',
  '11,773',
  '1,389',
  '39',
  '5,543',
  '16,967',
  '9,274',
  '2,085',
  '1,095',
  '104',
  '64,116',
  '2,084',
  '13,114',
  '21,107',
  '1,607',
  '3,965',
  '3,544',
  '17,642',
  '5,395',
  '4,664',
  '1,201',
  '5,602',
  '4',
  '55',
  '17,138',
  '814',
  '1,055',
  '790',
  '917',
  '480',
  '2,813',
  '23',
  '3,795',
  '734',
  '750',
  '27',
  '99',
  '1,060',
  '72',
  '160',
  '2,749',
  '8',
  '587',
  '58',
  '32',
  '298',
  '96',
  '158,619',
  '6',
  '2,496',
  '10',
  '644',
  '251',
  '14',
  '3,710',
  '107',
  '86',
  '12,926',
  '1,309',
  '22',
  '9',
  '855',
  '3,324',
  '55',
  '11,542',
  '310',
  '85',
  '18,057',
  '15',
  '1,052',
  '11',
  '382',
  '10,148',
  '56,478',
  '5,275',
  '857',
  '229',
  '3,376',
  '8,799',
  '732',
  '222',
  '739',
  '415',
  '207',
  '6',
  '1,744',
  '1,244',
  '1,278',
  '232',
  '11',
  '1,599',
  '781',
  '45',
  '424',
  '107',
  '6,796',
  '2,907',
  '127',
  '1,022',
  '3,303',
  '1,763',
  '3,580',
  '134',
  '19',
  '1,066',
  '640',
  '3,840',
  '4,888',
  '595',
  '799',
  '7,502',
  '1,547',
  '327',
  '3,212',
  '518',
  '4,201',
  '226',
  '38',
  '1,664',
  '7,987',
  '1,193',
  '12,592',
  '370',
  '1,078',
  '3,977',
  '9,144',
  '30,832',
  '38',
  '3,194',
  '460',
  '779',
  '35',
  '677'],
 '2016': ['1,051,031',
  '8,328',
  '4,653',
  '1,775',
  '-',
  '154',
  '22',
  '290',
  '3,730',
  '2,962',
  '38',
  '3,034',
  '474',
  '676',
  '725',
  '145',
  '13,570',
  '376',
  '1,994',
  '662',
  '772',
  '466',
  '112',
  '6,325',
  '1,626',
  '859',
  '61',
  '11,424',
  '21',
  '2,688',
  '575',
  '12,808',
  '351',
  '1,253',
  '1,868',
  '4,374',
  '12,673',
  '53',
  '234',
  '175',
  '1,596',
  '74,558',
  '17,316',
  '5',
  '5,345',
  '496',
  '2,029',
  '1,497',
  '348',
  '54,396',
  '22',
  '113',
  '637',
  '58',
  '609',
  '370',
  '229',
  '50,610',
  '10,187',
  '12,085',
  '19,487',
  '25',
  '2,220',
  '189',
  '11,394',
  '875',
  '407',
  '4,693',
  '14',
  '146',
  '1,142',
  '1,410',
  '5,436',
  '6,186',
  '1,211',
  '525',
  '11,773',
  '1,389',
  '39',
  '5,543',
  '16,967',
  '9,274',
  '2,085',
  '1,095',
  '104',
  '64,116',
  '2,084',
  '13,114',
  '21,107',
  '1,607',
  '3,965',
  '3,544',
  '17,642',
  '5,395',
  '4,664',
  '1,201',
  '5,602',
  '4',
  '55',
  '17,138',
  '814',
  '1,055',
  '790',
  '917',
  '480',
  '2,813',
  '23',
  '3,795',
  '734',
  '750',
  '27',
  '99',
  '1,060',
  '72',
  '160',
  '2,749',
  '8',
  '587',
  '58',
  '32',
  '298',
  '96',
  '158,619',
  '6',
  '2,496',
  '10',
  '644',
  '251',
  '14',
  '3,710',
  '107',
  '86',
  '12,926',
  '1,309',
  '22',
  '9',
  '855',
  '3,324',
  '55',
  '11,542',
  '310',
  '85',
  '18,057',
  '15',
  '1,052',
  '11',
  '382',
  '10,148',
  '56,478',
  '5,275',
  '857',
  '229',
  '3,376',
  '8,799',
  '732',
  '222',
  '739',
  '415',
  '207',
  '6',
  '1,744',
  '1,244',
  '1,278',
  '232',
  '11',
  '1,599',
  '781',
  '45',
  '424',
  '107',
  '6,796',
  '2,907',
  '127',
  '1,022',
  '3,303',
  '1,763',
  '3,580',
  '134',
  '19',
  '1,066',
  '640',
  '3,840',
  '4,888',
  '595',
  '799',
  '7,502',
  '1,547',
  '327',
  '3,212',
  '518',
  '4,201',
  '226',
  '38',
  '1,664',
  '7,987',
  '1,193',
  '12,592',
  '370',
  '1,078',
  '3,977',
  '9,144',
  '30,832',
  '38',
  '3,194',
  '460',
  '779',
  '35',
  '677'],
 '2017': ['1,051,031',
  '8,328',
  '4,653',
  '1,775',
  '-',
  '154',
  '22',
  '290',
  '3,730',
  '2,962',
  '38',
  '3,034',
  '474',
  '676',
  '725',
  '145',
  '13,570',
  '376',
  '1,994',
  '662',
  '772',
  '466',
  '112',
  '6,325',
  '1,626',
  '859',
  '61',
  '11,424',
  '21',
  '2,688',
  '575',
  '12,808',
  '351',
  '1,253',
  '1,868',
  '4,374',
  '12,673',
  '53',
  '234',
  '175',
  '1,596',
  '74,558',
  '17,316',
  '5',
  '5,345',
  '496',
  '2,029',
  '1,497',
  '348',
  '54,396',
  '22',
  '113',
  '637',
  '58',
  '609',
  '370',
  '229',
  '50,610',
  '10,187',
  '12,085',
  '19,487',
  '25',
  '2,220',
  '189',
  '11,394',
  '875',
  '407',
  '4,693',
  '14',
  '146',
  '1,142',
  '1,410',
  '5,436',
  '6,186',
  '1,211',
  '525',
  '11,773',
  '1,389',
  '39',
  '5,543',
  '16,967',
  '9,274',
  '2,085',
  '1,095',
  '104',
  '64,116',
  '2,084',
  '13,114',
  '21,107',
  '1,607',
  '3,965',
  '3,544',
  '17,642',
  '5,395',
  '4,664',
  '1,201',
  '5,602',
  '4',
  '55',
  '17,138',
  '814',
  '1,055',
  '790',
  '917',
  '480',
  '2,813',
  '23',
  '3,795',
  '734',
  '750',
  '27',
  '99',
  '1,060',
  '72',
  '160',
  '2,749',
  '8',
  '587',
  '58',
  '32',
  '298',
  '96',
  '158,619',
  '6',
  '2,496',
  '10',
  '644',
  '251',
  '14',
  '3,710',
  '107',
  '86',
  '12,926',
  '1,309',
  '22',
  '9',
  '855',
  '3,324',
  '55',
  '11,542',
  '310',
  '85',
  '18,057',
  '15',
  '1,052',
  '11',
  '382',
  '10,148',
  '56,478',
  '5,275',
  '857',
  '229',
  '3,376',
  '8,799',
  '732',
  '222',
  '739',
  '415',
  '207',
  '6',
  '1,744',
  '1,244',
  '1,278',
  '232',
  '11',
  '1,599',
  '781',
  '45',
  '424',
  '107',
  '6,796',
  '2,907',
  '127',
  '1,022',
  '3,303',
  '1,763',
  '3,580',
  '134',
  '19',
  '1,066',
  '640',
  '3,840',
  '4,888',
  '595',
  '799',
  '7,502',
  '1,547',
  '327',
  '3,212',
  '518',
  '4,201',
  '226',
  '38',
  '1,664',
  '7,987',
  '1,193',
  '12,592',
  '370',
  '1,078',
  '3,977',
  '9,144',
  '30,832',
  '38',
  '3,194',
  '460',
  '779',
  '35',
  '677']}

In [40]:
df1=pd.DataFrame(table3)
df2=pd.DataFrame(table4)

In [42]:
df1.to_csv('Table3.1.csv',index=False)
df2.to_csv('Table3.2.csv',index=False)