In [10]:
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen
url = 'https://www.dhs.gov/immigration-statistics/yearbook/2017/table2'
html=urlopen(url).read()
soup=BeautifulSoup(html,'html.parser')

In [48]:
table2 = {
    'Region and country of last residence':[],
    '2015':[],
    '2016':[],
    '2017':[]
    
}

In [49]:
table2

{'Region and country of last residence': [],
 '2015': [],
 '2016': [],
 '2017': []}

In [50]:
tables = soup.find_all('table')
rows = tables[0].findAll('tr')[1:]

In [51]:
for r in rows:
    r1=r.findAll('th')
    r2=r.findAll('td')
    table2['Region and country of last residence'].append(r1[0].get_text())
    table2['2015'].append(r2[0].string)
    table2['2016'].append(r2[1].string)
    table2['2017'].append(r2[2].string)

In [52]:
table2

{'Region and country of last residence': ['\xa0\xa0\xa0\xa0\xa0 Total',
  '\xa0\xa0 Europe',
  'Austria-Hungary 2,3',
  'Austria 2, 3',
  'Hungary 2, 3',
  'Belgium',
  'Bulgaria 4',
  'Czechoslovakia 5',
  'Denmark',
  'Finland 6',
  'France',
  'Germany 3',
  'Greece',
  'Ireland 7',
  'Italy',
  'Netherlands',
  'Norway-Sweden 8',
  'Norway 8',
  'Sweden 8',
  'Poland 3',
  'Portugal 9',
  'Romania',
  'Russia 3, 6,10',
  'Spain',
  'Switzerland',
  'United Kingdom 11',
  'Yugoslavia 12',
  '\xa0\xa0 Other Europe',
  '\xa0\xa0 Asia',
  'China',
  'Hong Kong',
  'India',
  'Iran',
  'Israel',
  'Japan',
  'Jordan',
  'Korea 13',
  'Philippines',
  'Syria 14',
  'Taiwan',
  'Turkey 14',
  'Vietnam',
  '\xa0\xa0 Other Asia',
  '\xa0\xa0 America',
  'Canada and Newfoundland 15,16,17',
  'Mexico 16,17',
  'Caribbean',
  'Cuba',
  'Dominican Republic',
  'Haiti',
  'Jamaica 18',
  'Other Caribbean 18',
  '\xa0\xa0 Central America',
  'Belize',
  'Costa Rica',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Nicaragua',
  'Panama 19',
  '\xa0\xa0 Other Central America',
  '\xa0\xa0 South America',
  'Argentina',
  'Bolivia',
  'Brazil',
  'Chile',
  'Colombia',
  'Ecuador',
  'Guyana',
  'Paraguay',
  'Peru',
  'Suriname',
  'Uruguay',
  'Venezuela',
  '\xa0\xa0 Other South America',
  '\xa0\xa0 Other America',
  'Africa',
  'Egypt',
  'Ethiopia',
  'Liberia',
  'Morocco',
  'South Africa',
  '\xa0\xa0 Other Africa',
  '\xa0\xa0 Oceania',
  'Australia 20',
  'New Zealand 20',
  'Other Oceania',
  'Not Specified 21'],
 '2015': ['1,051,031',
  '90,789',
  '2,965',
  '1,928',
  '1,037',
  '809',
  '2,585',
  '1,236',
  '634',
  '397',
  '5,034',
  '5,965',
  '1,330',
  '1,798',
  '3,829',
  '1,505',
  '1,551',
  '357',
  '1,194',
  '4,921',
  '869',
  '3,160',
  '9,030',
  '3,707',
  '1,007',
  '14,653',
  '4,721',
  '19,083',
  '405,854',
  '70,977',
  '2,426',
  '61,380',
  '9,074',
  '4,324',
  '5,808',
  '7,835',
  '16,976',
  '54,307',
  '5,459',
  '4,814',
  '8,762',
  '30,332',
  '123,380',
  '439,228',
  '19,309',
  '157,227',
  '146,086',
  '54,178',
  '50,382',
  '16,787',
  '17,362',
  '7,377',
  '46,556',
  '804',
  '2,121',
  '18,699',
  '11,466',
  '9,071',
  '3,262',
  '1,133',
  '-',
  '70,049',
  '3,542',
  '1,549',
  '11,247',
  '1,620',
  '16,509',
  '9,816',
  '5,313',
  '353',
  '9,973',
  '116',
  '1,023',
  '8,985',
  '3',
  '1',
  '98,677',
  '13,907',
  '12,566',
  '3,580',
  '3,569',
  '3,298',
  '61,757',
  '6,227',
  '3,795',
  '978',
  '1,454',
  '10,256'],
 '2016': ['1,183,505',
  '98,043',
  '2,620',
  '1,621',
  '999',
  '821',
  '2,560',
  '1,299',
  '562',
  '512',
  '5,473',
  '5,895',
  '1,664',
  '1,895',
  '4,385',
  '1,550',
  '1,729',
  '404',
  '1,325',
  '5,287',
  '1,017',
  '3,322',
  '9,280',
  '4,018',
  '1,090',
  '14,887',
  '5,392',
  '22,785',
  '442,854',
  '77,658',
  '2,982',
  '61,691',
  '9,596',
  '4,652',
  '5,709',
  '7,345',
  '21,329',
  '50,609',
  '3,800',
  '5,062',
  '8,635',
  '40,412',
  '143,374',
  '502,639',
  '19,349',
  '172,726',
  '180,479',
  '66,120',
  '60,613',
  '23,185',
  '22,833',
  '7,728',
  '54,512',
  '878',
  '2,295',
  '21,268',
  '12,548',
  '12,996',
  '3,397',
  '1,130',
  '-',
  '75,571',
  '3,783',
  '1,481',
  '13,528',
  '1,711',
  '16,830',
  '10,779',
  '4,909',
  '400',
  '10,519',
  '130',
  '911',
  '10,590',
  '-',
  '2',
  '110,754',
  '13,367',
  '13,699',
  '3,545',
  '4,447',
  '3,441',
  '72,255',
  '6,489',
  '4,173',
  '939',
  '1,377',
  '22,726'],
 '2017': ['1,127,167',
  '89,706',
  '2,886',
  '1,962',
  '924',
  '742',
  '2,070',
  '1,142',
  '536',
  '478',
  '4,973',
  '5,369',
  '1,495',
  '1,685',
  '4,055',
  '1,285',
  '1,523',
  '377',
  '1,146',
  '4,592',
  '910',
  '2,722',
  '8,841',
  '3,555',
  '837',
  '13,318',
  '4,966',
  '21,726',
  '404,371',
  '66,479',
  '2,893',
  '57,155',
  '9,311',
  '4,227',
  '5,176',
  '8,219',
  '18,559',
  '46,542',
  '3,010',
  '4,787',
  '9,144',
  '37,541',
  '131,328',
  '489,676',
  '18,469',
  '168,980',
  '173,724',
  '64,749',
  '58,384',
  '21,501',
  '21,517',
  '7,573',
  '52,907',
  '754',
  '2,259',
  '21,920',
  '12,792',
  '11,147',
  '3,014',
  '1,021',
  '-',
  '75,595',
  '3,191',
  '1,399',
  '14,832',
  '1,664',
  '16,341',
  '10,826',
  '4,683',
  '364',
  '9,767',
  '111',
  '952',
  '11,465',
  '-',
  '1',
  '116,667',
  '11,166',
  '15,678',
  '4,085',
  '4,066',
  '3,438',
  '78,234',
  '5,986',
  '3,818',
  '900',
  '1,268',
  '20,761']}

In [53]:
df=pd.DataFrame(table2)

In [54]:
df.to_csv('Table2.csv',index=False)